# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 464)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.drivePowerGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.drivePowerGroupBox.setFont(font)
        self.drivePowerGroupBox.setObjectName("drivePowerGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.drivePowerGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.drivePowerCheckBox = QtWidgets.QCheckBox(self.drivePowerGroupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.drivePowerCheckBox.setFont(font)
        self.drivePowerCheckBox.setChecked(False)
        self.drivePowerCheckBox.setObjectName("drivePowerCheckBox")
        self.horizontalLayout_2.addWidget(self.drivePowerCheckBox)
        self.gridLayout.addWidget(self.drivePowerGroupBox, 1, 0, 1, 1)
        self.jogPositionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.jogPositionGroupBox.setFont(font)
        self.jogPositionGroupBox.setObjectName("jogPositionGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.jogPositionGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.jogNegPushButton = QtWidgets.QPushButton(self.jogPositionGroupBox)
        self.jogNegPushButton.setObjectName("jogNegPushButton")
        self.horizontalLayout_3.addWidget(self.jogNegPushButton)
        self.jogPosPushButton = QtWidgets.QPushButton(self.jogPositionGroupBox)
        self.jogPosPushButton.setObjectName("jogPosPushButton")
        self.horizontalLayout_3.addWidget(self.jogPosPushButton)
        self.jogStepLineEdit = QtWidgets.QLineEdit(self.jogPositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogStepLineEdit.sizePolicy().hasHeightForWidth())
        self.jogStepLineEdit.setSizePolicy(sizePolicy)
        self.jogStepLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.jogStepLineEdit.setFont(font)
        self.jogStepLineEdit.setText("")
        self.jogStepLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jogStepLineEdit.setObjectName("jogStepLineEdit")
        self.horizontalLayout_3.addWidget(self.jogStepLineEdit)
        self.label = QtWidgets.QLabel(self.jogPositionGroupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.jogPosPushButton.raise_()
        self.jogNegPushButton.raise_()
        self.jogStepLineEdit.raise_()
        self.label.raise_()
        self.gridLayout.addWidget(self.jogPositionGroupBox, 2, 0, 1, 1)
        self.setToGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setToGroupBox.setFont(font)
        self.setToGroupBox.setObjectName("setToGroupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.setToGroupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.setToPushButton = QtWidgets.QPushButton(self.setToGroupBox)
        self.setToPushButton.setObjectName("setToPushButton")
        self.horizontalLayout_8.addWidget(self.setToPushButton)
        self.setToLineEdit = QtWidgets.QLineEdit(self.setToGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setToLineEdit.sizePolicy().hasHeightForWidth())
        self.setToLineEdit.setSizePolicy(sizePolicy)
        self.setToLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.setToLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.setToLineEdit.setFont(font)
        self.setToLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setToLineEdit.setText("")
        self.setToLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.setToLineEdit.setObjectName("setToLineEdit")
        self.horizontalLayout_8.addWidget(self.setToLineEdit)
        self.label_3 = QtWidgets.QLabel(self.setToGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addWidget(self.setToGroupBox, 0, 1, 1, 1)
        self.trackingModeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.trackingModeGroupBox.setFont(font)
        self.trackingModeGroupBox.setObjectName("trackingModeGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.trackingModeGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.trackingModeCheckBox = QtWidgets.QCheckBox(self.trackingModeGroupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.trackingModeCheckBox.setFont(font)
        self.trackingModeCheckBox.setObjectName("trackingModeCheckBox")
        self.horizontalLayout.addWidget(self.trackingModeCheckBox)
        self.gridLayout.addWidget(self.trackingModeGroupBox, 1, 1, 1, 1)
        self.moveToPositionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.moveToPositionGroupBox.setFont(font)
        self.moveToPositionGroupBox.setObjectName("moveToPositionGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.moveToPositionGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.moveToPushButton = QtWidgets.QPushButton(self.moveToPositionGroupBox)
        self.moveToPushButton.setObjectName("moveToPushButton")
        self.horizontalLayout_4.addWidget(self.moveToPushButton)
        self.moveToLineEdit = QtWidgets.QLineEdit(self.moveToPositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveToLineEdit.sizePolicy().hasHeightForWidth())
        self.moveToLineEdit.setSizePolicy(sizePolicy)
        self.moveToLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moveToLineEdit.setFont(font)
        self.moveToLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.moveToLineEdit.setObjectName("moveToLineEdit")
        self.horizontalLayout_4.addWidget(self.moveToLineEdit)
        self.label_2 = QtWidgets.QLabel(self.moveToPositionGroupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout.addWidget(self.moveToPositionGroupBox, 2, 1, 1, 1)
        self.stopGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopGroupBox.setFont(font)
        self.stopGroupBox.setObjectName("stopGroupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.stopGroupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget = QtWidgets.QWidget(self.stopGroupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.stopPushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopPushButton.setFont(font)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_5.addWidget(self.stopPushButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_9.addWidget(self.widget)
        self.gridLayout.addWidget(self.stopGroupBox, 3, 1, 1, 1)
        self.runGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.runGroupBox.setFont(font)
        self.runGroupBox.setObjectName("runGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.runGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.runGroupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.runPushButton = QtWidgets.QPushButton(self.widget_2)
        self.runPushButton.setObjectName("runPushButton")
        self.horizontalLayout_10.addWidget(self.runPushButton)
        self.runLineEdit = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runLineEdit.sizePolicy().hasHeightForWidth())
        self.runLineEdit.setSizePolicy(sizePolicy)
        self.runLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.runLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runLineEdit.setObjectName("runLineEdit")
        self.horizontalLayout_10.addWidget(self.runLineEdit)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.runGroupBox, 3, 0, 1, 1)
        self.currentPositionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentPositionGroupBox.setFont(font)
        self.currentPositionGroupBox.setObjectName("currentPositionGroupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.currentPositionGroupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.positionPollCheckBox = QtWidgets.QCheckBox(self.currentPositionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionPollCheckBox.sizePolicy().hasHeightForWidth())
        self.positionPollCheckBox.setSizePolicy(sizePolicy)
        self.positionPollCheckBox.setMaximumSize(QtCore.QSize(20, 16777215))
        self.positionPollCheckBox.setText("")
        self.positionPollCheckBox.setObjectName("positionPollCheckBox")
        self.horizontalLayout_7.addWidget(self.positionPollCheckBox)
        self.currentPositionLcdNumber = QtWidgets.QLCDNumber(self.currentPositionGroupBox)
        self.currentPositionLcdNumber.setAutoFillBackground(True)
        self.currentPositionLcdNumber.setSmallDecimalPoint(False)
        self.currentPositionLcdNumber.setDigitCount(6)
        self.currentPositionLcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.currentPositionLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.currentPositionLcdNumber.setObjectName("currentPositionLcdNumber")
        self.horizontalLayout_7.addWidget(self.currentPositionLcdNumber)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.gridLayout.addWidget(self.currentPositionGroupBox, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Autostep Proxy"))
        self.drivePowerGroupBox.setTitle(_translate("MainWindow", "Drive Power"))
        self.drivePowerCheckBox.setText(_translate("MainWindow", "Enable"))
        self.jogPositionGroupBox.setTitle(_translate("MainWindow", "Jog"))
        self.jogNegPushButton.setText(_translate("MainWindow", "-"))
        self.jogPosPushButton.setText(_translate("MainWindow", "+"))
        self.label.setText(_translate("MainWindow", "(deg)"))
        self.setToGroupBox.setTitle(_translate("MainWindow", "Set Position"))
        self.setToPushButton.setText(_translate("MainWindow", "Set To"))
        self.label_3.setText(_translate("MainWindow", "(deg)"))
        self.trackingModeGroupBox.setTitle(_translate("MainWindow", "Tracking Mode"))
        self.trackingModeCheckBox.setText(_translate("MainWindow", "Enable"))
        self.moveToPositionGroupBox.setTitle(_translate("MainWindow", "Move To"))
        self.moveToPushButton.setText(_translate("MainWindow", "Go"))
        self.label_2.setText(_translate("MainWindow", "(deg)"))
        self.stopGroupBox.setTitle(_translate("MainWindow", "Stop Motion Command"))
        self.stopPushButton.setText(_translate("MainWindow", "Stop"))
        self.runGroupBox.setTitle(_translate("MainWindow", "Constant Velocity"))
        self.runPushButton.setText(_translate("MainWindow", "Run"))
        self.label_4.setText(_translate("MainWindow", "(deg/s)"))
        self.currentPositionGroupBox.setTitle(_translate("MainWindow", "Current Position"))

